
services:
  postgres-dj:
    image: postgres:latest
    container_name: postgres-dj
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq-dj:
    image: rabbitmq:3-management
    container_name: rabbitmq-dj
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-dj:
    image: redis:latest
    container_name: redis-dj
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis123", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pyserver-dj:
    build: .
    image: caddy:2-alpine
    container_name: django-server
    working_dir: /app
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8001:8001"
      - "443:443"
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoProject.settings
      - DATABASE_URL=postgres://postgres:postgres@postgres-dj:5432/mydb
      - DEBUG=0
    depends_on:
      - postgres-dj
      - rabbitmq-dj
      - redis-dj
    command: >
      sh -c "apk add --no-cache python3 py3-pip
      && pip install -r requirements.txt gunicorn
      && python manage.py migrate
      && gunicorn DjangoProject.wsgi:application --bind 0.0.0.0:8000
      && caddy run --config /app/Caddyfile"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

